import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      style={{
        backgroundColor: "#DFEDEA",
      }}
      
      
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         
        <div className="min-h-screen  ">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}



